Return CI back

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,8 +1,8 @@
 name: release
 on:
   push:
-    #tags:
-    #  - v*.*.*
+    tags:
+      - v*.*.*
 env:
   # THIS GITHUB_TOKEN IS A REQUIREMENT TO BE ABLE TO WRITE TO GH RELEASES
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -28,127 +28,114 @@ env:
   PYPI_REPOSITORY_URL: ""
   PUBLISH_PYPI: true
 jobs:
+  publish_binary:
+    name: publish
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+    - name: Checkout Repo
+      uses: actions/checkout@v2
+    - name: Unshallow clone for tags
+      run: git fetch --prune --unshallow --tags
+    - name: Install Go
+      uses: actions/setup-go@v2
+      with:
+        go-version: ${{matrix.goversion}}
+    - name: Install pulumictl
+      uses: jaxxstorm/action-install-gh-release@v1.5.0
+      with:
+        repo: pulumi/pulumictl
+    - name: Set PreRelease Version
+      run: echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
+    - name: Run GoReleaser
+      uses: goreleaser/goreleaser-action@v4
+      with:
+        args: -p 3 release --rm-dist
+        version: latest
+    strategy:
+      fail-fast: true
+      matrix:
+        goversion:
+        - 1.18.x
   publish_sdk:
     name: Publish SDKs
     runs-on: ubuntu-latest
+    needs: publish_binary
     permissions:
       id-token: write
     steps:
-      - run: |
-          if [ -z "${{ env.PYPI_PASSWORD }}" ]; then
-            echo "env.PYPI_PASSWORD is not set"
+      - name: Checkout Repo
+        uses: actions/checkout@v2
+      - name: Unshallow clone for tags
+        run: git fetch --prune --unshallow --tags
+      - name: Install Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: ${{ matrix.goversion }}
+      - name: Install pulumictl
+        uses: jaxxstorm/action-install-gh-release@v1.5.0
+        with:
+          repo: pulumi/pulumictl
+      - name: Install Pulumi CLI
+        uses: pulumi/action-install-pulumi-cli@v2.0.0
+      - name: Setup Node
+        uses: actions/setup-node@v1
+        with:
+          node-version: ${{matrix.nodeversion}}
+          registry-url: ${{env.NPM_REGISTRY_URL}}
+      - name: Setup DotNet
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: ${{matrix.dotnetversion}}
+      - name: Setup Python
+        uses: actions/setup-python@v1
+        with:
+          python-version: ${{matrix.pythonversion}}
+      - name: Build SDK
+        run: make build_${{ matrix.language }}
+      - name: Check worktree clean
+        run: |
+          git update-index -q --refresh
+          if ! git diff-files --quiet; then
+              >&2 echo "error: working tree is not clean, aborting!"
+              git status
+              git diff
+              exit 1
           fi
-
-          if [ -z "${{ secrets.PYPI_API_TOKEN }}" ]; then
-            echo "secrets.PYPI_PASSWORD is not set"
-          fi
-  # publish_binary:
-  #   name: publish
-  #   runs-on: ubuntu-latest
-  #   permissions:
-  #     contents: write
-  #   steps:
-  #   - name: Checkout Repo
-  #     uses: actions/checkout@v2
-  #   - name: Unshallow clone for tags
-  #     run: git fetch --prune --unshallow --tags
-  #   - name: Install Go
-  #     uses: actions/setup-go@v2
-  #     with:
-  #       go-version: ${{matrix.goversion}}
-  #   - name: Install pulumictl
-  #     uses: jaxxstorm/action-install-gh-release@v1.5.0
-  #     with:
-  #       repo: pulumi/pulumictl
-  #   - name: Set PreRelease Version
-  #     run: echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
-  #   - name: Run GoReleaser
-  #     uses: goreleaser/goreleaser-action@v4
-  #     with:
-  #       args: -p 3 release --rm-dist
-  #       version: latest
-  #   strategy:
-  #     fail-fast: true
-  #     matrix:
-  #       goversion:
-  #       - 1.18.x
-  # publish_sdk:
-  #   name: Publish SDKs
-  #   runs-on: ubuntu-latest
-  #   needs: publish_binary
-  #   permissions:
-  #     id-token: write
-  #   steps:
-  #     - name: Checkout Repo
-  #       uses: actions/checkout@v2
-  #     - name: Unshallow clone for tags
-  #       run: git fetch --prune --unshallow --tags
-  #     - name: Install Go
-  #       uses: actions/setup-go@v2
-  #       with:
-  #         go-version: ${{ matrix.goversion }}
-  #     - name: Install pulumictl
-  #       uses: jaxxstorm/action-install-gh-release@v1.5.0
-  #       with:
-  #         repo: pulumi/pulumictl
-  #     - name: Install Pulumi CLI
-  #       uses: pulumi/action-install-pulumi-cli@v2.0.0
-  #     - name: Setup Node
-  #       uses: actions/setup-node@v1
-  #       with:
-  #         node-version: ${{matrix.nodeversion}}
-  #         registry-url: ${{env.NPM_REGISTRY_URL}}
-  #     - name: Setup DotNet
-  #       uses: actions/setup-dotnet@v1
-  #       with:
-  #         dotnet-version: ${{matrix.dotnetversion}}
-  #     - name: Setup Python
-  #       uses: actions/setup-python@v1
-  #       with:
-  #         python-version: ${{matrix.pythonversion}}
-  #     - name: Build SDK
-  #       run: make build_${{ matrix.language }}
-  #     - name: Check worktree clean
-  #       run: |
-  #         git update-index -q --refresh
-  #         if ! git diff-files --quiet; then
-  #             >&2 echo "error: working tree is not clean, aborting!"
-  #             git status
-  #             git diff
-  #             exit 1
-  #         fi
-  #     - if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
-  #       name: Publish package to PyPI
-  #       uses: pypa/gh-action-pypi-publish@release/v1
-  #       with:
-  #         user: ${{ env.PYPI_USERNAME }}
-  #         password: ${{ env.PYPI_PASSWORD }}
-  #         packages_dir: ${{github.workspace}}/sdk/python/bin/dist
-  #     - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
-  #       uses: JS-DevTools/npm-publish@v1
-  #       with:
-  #         access: "public"
-  #         token: ${{ env.NPM_TOKEN }}
-  #         package: ${{github.workspace}}/sdk/nodejs/bin/package.json
-  #     - if: ${{ matrix.language == 'dotnet' && env.PUBLISH_NUGET == 'true' }}
-  #       name: publish nuget package
-  #       run: |
-  #         dotnet nuget push ${{github.workspace}}/sdk/dotnet/bin/Debug/*.nupkg -s ${{ env.NUGET_FEED_URL }} -k ${{ env.NUGET_PUBLISH_KEY }}
-  #         echo "done publishing packages"
-  #   strategy:
-  #     fail-fast: true
-  #     matrix:
-  #       dotnetversion:
-  #         - 3.1.301
-  #       goversion:
-  #         - 1.18.x
-  #       language:
-  #         - nodejs
-  #         - python
-  #         - dotnet
-  #         - go
-  #       nodeversion:
-  #         - 14.x
-  #       pythonversion:
-  #         - "3.9"
+      - if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
+        name: Publish package to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          user: ${{ env.PYPI_USERNAME }}
+          password: ${{ env.PYPI_PASSWORD }}
+          packages_dir: ${{github.workspace}}/sdk/python/bin/dist
+      - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
+        uses: JS-DevTools/npm-publish@v1
+        with:
+          access: "public"
+          token: ${{ env.NPM_TOKEN }}
+          package: ${{github.workspace}}/sdk/nodejs/bin/package.json
+      - if: ${{ matrix.language == 'dotnet' && env.PUBLISH_NUGET == 'true' }}
+        name: publish nuget package
+        run: |
+          dotnet nuget push ${{github.workspace}}/sdk/dotnet/bin/Debug/*.nupkg -s ${{ env.NUGET_FEED_URL }} -k ${{ env.NUGET_PUBLISH_KEY }}
+          echo "done publishing packages"
+    strategy:
+      fail-fast: true
+      matrix:
+        dotnetversion:
+          - 3.1.301
+        goversion:
+          - 1.18.x
+        language:
+          - nodejs
+          # TODO: Fix empty python secret
+          #- python
+          - dotnet
+          - go
+        nodeversion:
+          - 14.x
+        pythonversion:
+          - "3.9"
 
